/* Generated by the Systemtap dtrace wrapper */

#define STAP_HAS_SEMAPHORES 1


#include <sys/sdt.h>

/* TCL_PROC_ENTRY ( char* name, int objc, Tcl_Obj **objv) */
#define TCL_PROC_ENTRY_ENABLED() proc__entry_semaphore
__extension__ extern unsigned short proc__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_ENTRY(arg1,arg2,arg3) \
STAP_PROBE3(provider,proc__entry,arg1,arg2,arg3)

/* TCL_PROC_RETURN ( char* name, int code) */
#define TCL_PROC_RETURN_ENABLED() proc__return_semaphore
__extension__ extern unsigned short proc__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_RETURN(arg1,arg2) \
STAP_PROBE2(provider,proc__return,arg1,arg2)

/* TCL_PROC_RESULT ( char* name, int code, char* result, Tcl_Obj *resultobj) */
#define TCL_PROC_RESULT_ENABLED() proc__result_semaphore
__extension__ extern unsigned short proc__result_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_RESULT(arg1,arg2,arg3,arg4) \
STAP_PROBE4(provider,proc__result,arg1,arg2,arg3,arg4)

/* TCL_PROC_ARGS ( char* name, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, char* arg6, char* arg7, char* arg8, char* arg9) */
#define TCL_PROC_ARGS_ENABLED() proc__args_semaphore
__extension__ extern unsigned short proc__args_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_ARGS(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10) \
STAP_PROBE10(provider,proc__args,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10)

/* TCL_PROC_INFO ( char* cmd, char* type, char* proc, char* file, int line, int level) */
#define TCL_PROC_INFO_ENABLED() proc__info_semaphore
__extension__ extern unsigned short proc__info_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_PROC_INFO(arg1,arg2,arg3,arg4,arg5,arg6) \
STAP_PROBE6(provider,proc__info,arg1,arg2,arg3,arg4,arg5,arg6)

/* TCL_CMD_ENTRY ( char* name, int objc, Tcl_Obj **objv) */
#define TCL_CMD_ENTRY_ENABLED() cmd__entry_semaphore
__extension__ extern unsigned short cmd__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_ENTRY(arg1,arg2,arg3) \
STAP_PROBE3(provider,cmd__entry,arg1,arg2,arg3)

/* TCL_CMD_RETURN ( char* name, int code) */
#define TCL_CMD_RETURN_ENABLED() cmd__return_semaphore
__extension__ extern unsigned short cmd__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_RETURN(arg1,arg2) \
STAP_PROBE2(provider,cmd__return,arg1,arg2)

/* TCL_CMD_RESULT ( char* name, int code, char* result, Tcl_Obj *resultobj) */
#define TCL_CMD_RESULT_ENABLED() cmd__result_semaphore
__extension__ extern unsigned short cmd__result_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_RESULT(arg1,arg2,arg3,arg4) \
STAP_PROBE4(provider,cmd__result,arg1,arg2,arg3,arg4)

/* TCL_CMD_ARGS ( char* name, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, char* arg6, char* arg7, char* arg8, char* arg9) */
#define TCL_CMD_ARGS_ENABLED() cmd__args_semaphore
__extension__ extern unsigned short cmd__args_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_ARGS(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10) \
STAP_PROBE10(provider,cmd__args,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10)

/* TCL_CMD_INFO ( char* cmd, char* type, char* proc, char* file, int line, int level) */
#define TCL_CMD_INFO_ENABLED() cmd__info_semaphore
__extension__ extern unsigned short cmd__info_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_CMD_INFO(arg1,arg2,arg3,arg4,arg5,arg6) \
STAP_PROBE6(provider,cmd__info,arg1,arg2,arg3,arg4,arg5,arg6)

/* TCL_INST_START ( char* name, int depth, Tcl_Obj **stack) */
#define TCL_INST_START_ENABLED() inst__start_semaphore
__extension__ extern unsigned short inst__start_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_INST_START(arg1,arg2,arg3) \
STAP_PROBE3(provider,inst__start,arg1,arg2,arg3)

/* TCL_INST_DONE ( char* name, int depth, Tcl_Obj **stack) */
#define TCL_INST_DONE_ENABLED() inst__done_semaphore
__extension__ extern unsigned short inst__done_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_INST_DONE(arg1,arg2,arg3) \
STAP_PROBE3(provider,inst__done,arg1,arg2,arg3)

/* TCL_OBJ_CREATE ( Tcl_Obj* obj) */
#define TCL_OBJ_CREATE_ENABLED() obj__create_semaphore
__extension__ extern unsigned short obj__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_OBJ_CREATE(arg1) \
STAP_PROBE1(provider,obj__create,arg1)

/* TCL_OBJ_FREE ( Tcl_Obj* obj) */
#define TCL_OBJ_FREE_ENABLED() obj__free_semaphore
__extension__ extern unsigned short obj__free_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_OBJ_FREE(arg1) \
STAP_PROBE1(provider,obj__free,arg1)

/* TCL_TCL_PROBE ( char* arg0, char* arg1, char* arg2, char* arg3, char* arg4, char* arg5, char* arg6, char* arg7, char* arg8, char* arg9) */
#define TCL_TCL_PROBE_ENABLED() tcl__probe_semaphore
__extension__ extern unsigned short tcl__probe_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define TCL_TCL_PROBE(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10) \
STAP_PROBE10(provider,tcl__probe,arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10)

