// This file is generated by kconfig_compiler from kcm_kdnssd.kcfg.
// All changes you do to this file will be lost.
#ifndef DNSSD_CONFIGURATION_H
#define DNSSD_CONFIGURATION_H

#include <dnssd/dnssd_export.h>

#include <kconfigskeleton.h>
#include <kdebug.h>

namespace DNSSD {

class KDNSSD_EXPORT Configuration : public KConfigSkeleton
{
  public:

    static Configuration *self();
    ~Configuration();

    /**
      Set Additional domains for browsing
    */
    static
    void setDomainList( const QStringList & v )
    {
      if (!self()->isImmutable( QString::fromLatin1( "DomainList" ) ))
        self()->mDomainList = v;
    }

    /**
      Get Additional domains for browsing
    */
    static
    QStringList domainList()
    {
      return self()->mDomainList;
    }

  protected:
    Configuration();
    friend class ConfigurationHelper;


    // browsing
    QStringList mDomainList;

  private:
};

}

#endif

