/* Generated by the Systemtap dtrace wrapper */

#define STAP_HAS_SEMAPHORES 1


#include <sys/sdt.h>

/* PYTHON_FUNCTION_ENTRY ( const char *, const char *, int) */
#define PYTHON_FUNCTION_ENTRY_ENABLED() function__entry_semaphore
__extension__ extern unsigned short function__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_FUNCTION_ENTRY(arg1,arg2,arg3) \
STAP_PROBE3(provider,function__entry,arg1,arg2,arg3)

/* PYTHON_FUNCTION_RETURN ( const char *, const char *, int) */
#define PYTHON_FUNCTION_RETURN_ENABLED() function__return_semaphore
__extension__ extern unsigned short function__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define PYTHON_FUNCTION_RETURN(arg1,arg2,arg3) \
STAP_PROBE3(provider,function__return,arg1,arg2,arg3)

